config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :works, except: [:show]
  get 'angular-items', to: 'works#angular', as: 'angular_show'
  get 'portfolio/:id', to: 'works#show', as: 'portfolio_show'

  #get 'pages/about', as: "about"
  get 'about', to: 'pages#about'
  #get 'pages/contact', as: "contact"
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/share/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Enrique Nares</h3>
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: "nav-link active" %>
      <%= link_to "About", about_path, class: "nav-link" %>
      <%= link_to "Contact", contact_path, class: "nav-link" %>
      <%= link_to "Blog", blogs_path, class: "nav-link" %>
      <%= link_to "Portfolio", works_path, class: "nav-link" %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/share/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= link_to "Home", root_path, class: "nav-link" %>
      <%= link_to "About", about_path, class: "nav-link" %>
      <%= link_to "Contact", contact_path, class: "nav-link" %>
      <%= link_to "Blog", blogs_path, class: "nav-link active" %>
      <%= link_to "Portfolio", works_path, class: "nav-link" %>
      <%= login_helper 'nav-link'%>
    </nav>
  </div>
</div>

app/views/share/_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/share/_nav.html.erb
<div class="<%= location %>">
  <div class=""><%= link_to "Home", root_path %></div>
  <div class=""><%= link_to "About", about_path %></div>
  <div class=""><%= link_to "Contact", contact_path %></div>
  <div class=""><%= link_to "Blog", blogs_path %></div>
  <div class=""><%= link_to "Portfolio", works_path %></div>
</div>