config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :works, except: [:show]
  get 'angular-items', to: 'works#angular', as: 'angular_show'
  get 'portfolio/:id', to: 'works#show', as: 'portfolio_show'

  #get 'pages/about', as: "about"
  get 'about', to: 'pages#about'
  #get 'pages/contact', as: "contact"
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/work.rb
class Work < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

  #Create a custom scope
  def self.angular
    where(subtitle: "Angular JS")
  end

  scope :ruby_on_rails_work_items, -> {where(subtitle: 'Ruby on Rails')}
  # end of custom scope

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(600, 400)
    self.thumb_image ||= Placeholder.image_generator(350, 250)
    ## Equal to do
    ##if self.main_image == nil
    ##  self.main_image = "http://placehold.it/350x200"
    ##end

  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  layout 'work'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @works_item = Work.all # create a scope ->ruby_on_rails_work_items  #where(subtitle: "Angular JS")
    @page_title = "My portfolio Item"
  end

  def angular
    @angular_portfolio_items = Work.angular
  end

  def new
    @works_item = Work.new
    3.times {@works_item.technologies.build}
  end


  def destroy
    @works_item.destroy
    respond_to do |format|
      format.html{ redirect_to works_url, notice: "Post was removed."}
      format.json{ head :no_content}
    end
  end

  def create
    @works_item = Work.new(work_params)
    respond_to do |format|
      if @works_item.save
        format.html { redirect_to portfolio_show_path(@works_item.id), notice: "Your portfolio item is created"}
      else
        format.html {render :new}
      end
    end
  end

  def edit
      3.times {@works_item.technologies.build}
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @works_item.update(work_params)
        format.html { redirect_to works_url, notice: 'Work Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @works_item}
      else
        format.html { render :edit }
        format.json { render json: @works_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

  def work_params
    self.params.require(:work).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                    )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_work
    @works_item = Work.find(params[:id])
  end

end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@works_item) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_area :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.fields_for :technologies do |technology_form| %>
        <div>
        <p>Technology Name: <%= technology_form.text_field :name %></p>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/_work_item.html.erb
<h2><%= link_to "#{work_item.title}", work_path(work_item.id) %></h2>
<h3><%= work_item.subtitle %></h3>
<p><%= work_item.body %></p>
<%= image_tag work_item.thumb_image unless work_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_work_path(work_item.id) if logged_in?(:site_admin) %>
  <%= link_to "Show", portfolio_show_path(work_item.id) %>
  <%= link_to "Delete", work_path(work_item), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>

app/views/works/angular.html.erb
<h1>Angular Items</h1>

<%= link_to "All Works", works_path %>

<% @angular_portfolio_items.each do |work| %>
  <h2><%= link_to "#{work.title}", work_path(work.id) %></h2>
  <h3><%= work.subtitle %></h3>
  <p><%= work.body %></p>
  <%= image_tag work.thumb_image unless work.thumb_image.nil? %>
    <%= link_to "Edit", edit_work_path(work.id) if logged_in?(:site_admin)%>
    <%= link_to "Show", portfolio_show_path(work.id) %>
    <%= link_to "Delete", work_path(work), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin)%>
<% end %>

<%= link_to "Create New Item", new_work_path %>

app/views/works/edit.html.erb
<h1>Edit Portfolio Item</h1>
<%= render 'form', portfolio_item: @works_item %>

app/views/works/index.html.erb
<h1>Portfolio Items</h1>
<%= link_to 'Angular Posts', angular_show_path %>
<%= link_to "Create New Item", new_work_path if logged_in?(:site_admin) %>

<%= render partial: 'work_item', collection: @works_item %>

app/views/works/new.html.erb
<h1>Create New Portfolio Item</h1>
<%= render 'form', portfolio_item: @works_item %>

app/views/works/show.html.erb
<h1><%= @works_item.title %></h1>
  <h2><%=  @works_item.subtitle %></h2>
  <p><%=  @works_item.body %></p>
  <%= image_tag @works_item.main_image if !@works_item.main_image.nil? %>
  <%= link_to "Edit", edit_work_path(@works_item.id) if logged_in?(:site_admin) %>
<h2>Technologies Used: <h2>
  <% @works_item.technologies.each do |t| %>
  <p><%= t.name %></p>
  <% end %>